
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      T Diagnosa      <small><?= cclang('detail', ['T Diagnosa']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/t_diagnosa'); ?>">T Diagnosa</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">T Diagnosa</h3>
                     <h5 class="widget-user-desc">Detail T Diagnosa</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_t_diagnosa" id="form_t_diagnosa" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Iddiag </label>

                        <div class="col-sm-8">
                           <?= _ent($t_diagnosa->iddiag); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Noreg </label>

                        <div class="col-sm-8">
                           <?= _ent($t_diagnosa->noreg); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Subjective </label>

                        <div class="col-sm-8">
                           <?= _ent($t_diagnosa->subjective); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Diagnosa Awal (ICD) </label>

                        <div class="col-sm-8">
                           <?= _ent($t_diagnosa->description); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Objective </label>

                        <div class="col-sm-8">
                           <?= _ent($t_diagnosa->objective); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Asessment </label>

                        <div class="col-sm-8">
                           <?= _ent($t_diagnosa->asessment); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Planning </label>

                        <div class="col-sm-8">
                           <?= _ent($t_diagnosa->plan); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Diagnosa Akhir (ICD) </label>

                        <div class="col-sm-8">
                           <?= _ent($t_diagnosa->description); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Createby </label>

                        <div class="col-sm-8">
                           <?= _ent($t_diagnosa->createby); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Createdate </label>

                        <div class="col-sm-8">
                           <?= _ent($t_diagnosa->createdate); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('t_diagnosa_update', function() use ($t_diagnosa){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit t_diagnosa (Ctrl+e)" href="<?= site_url('administrator/t_diagnosa/edit/'.$t_diagnosa->iddiag); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['T Diagnosa']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/t_diagnosa/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['T Diagnosa']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
